// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/activity/index.vue')['default']
    Calendar: typeof import('./src/components/calendar/index.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    Media: typeof import('./src/components/media/index.vue')['default']
    Product: typeof import('./src/components/product/index.vue')['default']
    Store: typeof import('./src/components/store/index.vue')['default']
    StoreDetail: typeof import('./src/components/store/StoreDetail.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanRow: typeof import('vant/es')['Row']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
