/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'home': RouteRecordInfo<'home', '/:uniacid(\\d+)/', Record<never, never>, Record<never, never>>,
    'QiyueEventDetail': RouteRecordInfo<'QiyueEventDetail', '/:uniacid(\\d+)/qiyue-event/detail', Record<never, never>, Record<never, never>>,
    'QiyueEventHome': RouteRecordInfo<'QiyueEventHome', '/:uniacid(\\d+)/qiyue-event/home', Record<never, never>, Record<never, never>>,
    'QiyueEventMy': RouteRecordInfo<'QiyueEventMy', '/:uniacid(\\d+)/qiyue-event/my', Record<never, never>, Record<never, never>>,
    'QiyueEventOperatorBinding': RouteRecordInfo<'QiyueEventOperatorBinding', '/:uniacid(\\d+)/qiyue-event/operator/binding', Record<never, never>, Record<never, never>>,
    'QiyueEventOperatorVerify': RouteRecordInfo<'QiyueEventOperatorVerify', '/:uniacid(\\d+)/qiyue-event/operator/verify', Record<never, never>, Record<never, never>>,
    'QiyueEventSignup': RouteRecordInfo<'QiyueEventSignup', '/:uniacid(\\d+)/qiyue-event/signup', Record<never, never>, Record<never, never>>,
    'QiyueProAuthLogin': RouteRecordInfo<'QiyueProAuthLogin', '/:uniacid(\\d+)/qiyue-pro/auth/login', Record<never, never>, Record<never, never>>,
    'QiyueProAuthRedirect': RouteRecordInfo<'QiyueProAuthRedirect', '/:uniacid(\\d+)/qiyue-pro/auth/redirect', Record<never, never>, Record<never, never>>,
    'QiyueProHome': RouteRecordInfo<'QiyueProHome', '/:uniacid(\\d+)/qiyue-pro/home', Record<never, never>, Record<never, never>>,
    'QiyueProUcenter': RouteRecordInfo<'QiyueProUcenter', '/:uniacid(\\d+)/qiyue-pro/ucenter', Record<never, never>, Record<never, never>>,
    'QiyueProUcenterBinding': RouteRecordInfo<'QiyueProUcenterBinding', '/:uniacid(\\d+)/qiyue-pro/ucenter/binding', Record<never, never>, Record<never, never>>,
    'QiyueProUcenterHistory': RouteRecordInfo<'QiyueProUcenterHistory', '/:uniacid(\\d+)/qiyue-pro/ucenter/history', Record<never, never>, Record<never, never>>,
    'QiyueProUcenterProfile': RouteRecordInfo<'QiyueProUcenterProfile', '/:uniacid(\\d+)/qiyue-pro/ucenter/profile', Record<never, never>, Record<never, never>>,
  }
}
