/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'home': RouteRecordInfo<'home', '/:uniacid(\\d+)/', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/:uniacid(\\d+)/auth/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/:uniacid(\\d+)/auth/login', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/:uniacid(\\d+)/auth/register', Record<never, never>, Record<never, never>>,
    'qiyue-event': RouteRecordInfo<'qiyue-event', '/:uniacid(\\d+)/qiyue-event', Record<never, never>, Record<never, never>>,
    'qiyue-pro': RouteRecordInfo<'qiyue-pro', '/:uniacid(\\d+)/qiyue-pro', Record<never, never>, Record<never, never>>,
    'ucenter': RouteRecordInfo<'ucenter', '/:uniacid(\\d+)/ucenter', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/:uniacid(\\d+)/ucenter/profile', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/:uniacid(\\d+)/ucenter/settings', Record<never, never>, Record<never, never>>,
  }
}
